// Hand-transcribed course-level reference material (course outlines, lecture
// outlines, activity plans) — static data in the same spirit as
// legalSkills.js: not fetched live, not derived from the timetable sheet.
// Keyed by course code; a code with no entry here means every dashboard
// section that reads from this file simply renders nothing extra for it —
// that's the whole compatibility story for every course besides PCLL8010
// today. Session entries are keyed by "LG"/"SG" + number with NO trailing
// letter ("LG1", not "LG1A") — course.js resolves which part ("A"/"B") from
// the live timetable event's own `no` field (e.g. "LG1A"), not from here.
window.COURSE_DETAILS = {
  PCLL8010: {
    name: 'Civil Litigation',

    coordinators: [
      { name: 'Ophelia Chan', room: 'CCT 6.15', hours: 'Wednesdays 11am-5pm', email: 'cyyo@hku.hk' },
      { name: 'Sam Liu', room: 'CCT 9.05', hours: 'Mondays 3-6pm', email: 'shanliu2@hku.hk' },
      { name: 'Vivian Chan', room: 'CCT 7.15', hours: 'Wednesdays 11:30am-12:30pm & 5:30-6:30pm', email: 'vicmchan@hku.hk' },
    ],

    description: "This course introduces students to the procedural rules, core skills, and practical considerations involved in conducting civil litigation in Hong Kong. It integrates the teaching of procedural law with practical skills training in interviewing, drafting, and case analysis. Students will work with realistic case files in both contract and negligence contexts, developing competence in core litigation tasks such as taking instructions, preparing letters before action, conducting client interviews, effecting service, obtaining default judgments, and drafting pleadings.",

    learningOutcomes: [
      'Demonstrate sufficient knowledge and understanding of the procedural rules for conducting a civil action in the High Court and the District Court in Hong Kong',
      'Integrate their knowledge and understanding of the procedural rules for conducting a civil action with the core litigation skills',
      'Investigate and analyse factual and evidential issues',
      'Analyse legal issues and conduct practical legal research',
      'Draft basic contentious litigation documents such as letters before action, pleadings, affidavits, summonses and orders',
      'Conduct interviews with clients',
      "Gain familiarity with 'real-life' case files",
    ],

    attendance: {
      lectures: 'Not compulsory — strongly advised in person, but recordings are a supplementary revision tool, not a substitute for participation.',
      smallGroups: 'Compulsory. Any absence must be notified in advance (or as soon as possible), with reasons and supporting documents where appropriate.',
      notifyEmail: 'ftpcll@hku.hk',
    },

    materials: [
      'Civil Procedure in Hong Kong by Cheung, Chim and Meggitt (7th Edition, LexisNexis 2023)',
      'Case Files (Contract and Negligence)',
      'Large Group (LG) Lecture Outlines',
      'Small Group (SG) Activity Plans',
      'High Court Ordinance and District Court Ordinance, incl. Rules of the High Court / District Court (online)',
      'Hong Kong Civil Court Practice — Desk Edition ("Blue Book") (Butterworths) — annotated Rules of the High Court, available via Lexis',
      'Hong Kong Civil Procedure ("White Book") (Sweet & Maxwell) — the leading practitioner text, available via Westlaw',
    ],
    materialsNotes: [
      'Textbooks date quickly — check the latest case law rather than relying on the book alone.',
      'Electronic research access: the White Book, Hong Kong Law Reports and unreported judgments via Westlaw; the Hong Kong Cases series via Lexis; all Hong Kong legislation via BLIS; judgments and Practice Directions via the Judiciary website.',
      'Copyright: photocopying textbooks or commercially annotated statutes (e.g. the Blue Book) is not allowed — government-published statutes may be freely copied for personal use, but annotated commercial editions may not.',
    ],

    aiPolicy: "The use of generative AI tools (ChatGPT, Gemini, Copilot, etc.) is subject to HKU's policies. Unauthorised or undisclosed use may constitute academic misconduct or plagiarism — any content not the student's own must be appropriately cited, whether generated by another person or an AI tool. Breaches may result in disciplinary action.",

    assessments: [
      {
        title: 'Standardised Client Interview Assessment',
        weight: '5%',
        dateLabel: '17 or 18 September 2026',
        note: 'Allocation posted to Moodle',
        deadlineIds: ['PCLL8010-interview-1', 'PCLL8010-interview-2'],
      },
      { title: 'Final Examination — Knowledge', weight: '47.5%', dateLabel: '8 January 2027 (Provisional)' },
      { title: 'Final Examination — Drafting', weight: '47.5%', dateLabel: '9 January 2027 (Provisional)' },
    ],
    assessmentNotes: [
      'To pass, you need at least 50% in aggregate across the written assessments (Knowledge + Drafting + the interviewing exercise) — you do not need to pass each paper individually.',
      'Two thresholds must both be cleared: 50%+ overall (written papers plus the interviewing exercise), AND 50%+ of the written-papers component alone (47.5 out of 95) — a strong interview mark cannot rescue weak written papers. Example: 5/5 on the interview plus 46/95 on the written papers is 51/100 overall, which looks like a pass, but still fails because 46 is under 47.5.',
      'Re-examinations (if allowed) only require re-sitting the paper(s) where you scored below 50% of that paper’s marks; marks from papers you already passed (and the interviewing exercise) carry over.',
      'PCLL8010 = 70% Civil Litigation + 30% Civil Advocacy.',
    ],

    // Each homework/todo item's due date lives ONLY here (referenced by id
    // from homework[]/todos[] below) — one place any date ever needs
    // updating. `kind` drives both the deadline-chip color and which
    // localStorage checklist a "done" check reads from.
    deadlines: [
      { id: 'PCLL8010-hw-sg1', courseCode: 'PCLL8010', kind: 'homework', refId: 'hw-sg1', date: '2026-09-25', time: '17:30', title: 'LBA due (SG1 homework)' },
      { id: 'PCLL8010-hw-sg4', courseCode: 'PCLL8010', kind: 'homework', refId: 'hw-sg4', date: '2026-10-27', title: 'Statement of Claim due (SG4 homework)' },
      { id: 'PCLL8010-hw-sg7', courseCode: 'PCLL8010', kind: 'homework', refId: 'hw-sg7', date: '2026-11-17', title: 'Draft Affirmation & Order due (SG7 homework)' },
      { id: 'PCLL8010-hw-sg8', courseCode: 'PCLL8010', kind: 'homework', refId: 'hw-sg8', date: '2026-12-01', title: 'Draft Affidavit (Mareva) due (SG8 homework)' },
      { id: 'PCLL8010-undertaking', courseCode: 'PCLL8010', kind: 'todo', refId: 'todo-undertaking', date: '2026-09-11', time: '17:00', title: 'Undertaking Form deadline (if not handed in at SG1)' },
      { id: 'PCLL8010-interview-1', courseCode: 'PCLL8010', kind: 'assessment', refId: 'assessment-interview', date: '2026-09-17', title: 'Standardised Client Interview — check your allocated slot' },
      { id: 'PCLL8010-interview-2', courseCode: 'PCLL8010', kind: 'assessment', refId: 'assessment-interview', date: '2026-09-18', title: 'Standardised Client Interview — check your allocated slot' },
    ],

    homework: [
      { id: 'hw-sg1', title: 'Letter before action', sgRef: 'SG1', mode: 'One draft per subgroup', feedback: 'Oral feedback during a later SG', deadlineId: 'PCLL8010-hw-sg1' },
      { id: 'hw-sg4', title: 'Statement of Claim — Negligence', sgRef: 'SG4', mode: 'Individual submission', feedback: 'Individual written feedback', deadlineId: 'PCLL8010-hw-sg4' },
      { id: 'hw-sg7', title: 'Draft Affirmation and Draft Order', sgRef: 'SG7', mode: 'One draft per subgroup', feedback: 'Oral feedback during a later SG', deadlineId: 'PCLL8010-hw-sg7' },
      { id: 'hw-sg8', title: 'Draft Affidavit in Support of Mareva Injunction', sgRef: 'SG8', mode: 'Individual submission', feedback: 'Individual written feedback', deadlineId: 'PCLL8010-hw-sg8' },
    ],

    todos: [
      { id: 'todo-undertaking', title: 'Submit Interviewing Exercise Undertaking Form', deadlineId: 'PCLL8010-undertaking' },
    ],

    // Content shared by more than one session — referenced by id from a
    // session's `referenceIds`, never duplicated inline.
    references: {
      proFormaDeclaration: {
        title: 'Pro Forma Declaration',
        body: "Every written assignment must be submitted with a signed pro forma declaration (that you did not consult previous years' materials/sample drafts, and did not look at other groups' drafts) — without it, the assignment is treated as a non-submission.",
        bullets: [
          'Submit it as the front page of the SAME Word document as your assignment — one file, not a separate attachment.',
          'Typing your name at the top and bottom of the declaration counts as signing it.',
          'Put your name and group number in the top-left corner of the assignment itself.',
        ],
      },
      skillsGuideLBA: {
        title: 'Skills Guide — Drafting a Letter Before Action',
        sections: [
          {
            heading: 'Presentation (30%)',
            items: [
              'Appropriate opening/closing formalities, visual cues and signpost words',
              'Appropriate language for the addressee — active voice, no contractions, no legalese, no vague phrases',
              'Good use of headings, sub-headings, paragraphs',
              'Logical structure with an appropriate opening and conclusion',
              'Consistent tone and style; succinct, clear and precise',
            ],
          },
          {
            heading: 'Aim & Purpose',
            items: [
              'Simple, straightforward English that conveys purpose clearly',
              "Identify the letter's central (and secondary) purposes before drafting",
              'Start by outlining the points to include',
            ],
          },
          {
            heading: 'Contents (40%)',
            items: [
              'Explains on whose behalf the firm is instructed',
              'Sets out the relevant background to the claim in sufficient detail',
              'Includes the cause of action',
              'Summarises loss/damage/injury and deals with quantum',
              "Contains clear proposals for settling the claim that meet the client's objectives",
              'Makes clear that proceedings will follow if the recipient does not comply (if instructed)',
            ],
          },
          {
            heading: 'Other points to bear in mind',
            items: [
              'Put yourself in the position of the reader',
              "Be positive and firm asserting the client's position",
              'Edit hard — the shorter the letter, the greater the impact',
              'Every word should add to or explain the message; remove the rest',
              'Check grammar, spelling and punctuation carefully',
            ],
          },
          {
            heading: 'Overall (30%)',
            items: ["Set out the client's claim clearly, without prejudicing their interests"],
          },
        ],
      },
      lbaStudentGuide: {
        title: 'Student Guide — Drafting an LBA in a Simple Contract Dispute',
        sections: [
          {
            heading: 'Purpose & tone',
            items: [
              'An LBA places the recipient on notice of the claim and invites resolution without court proceedings — firm and authoritative, but professional and respectful; a lawyer is a problem-solver and negotiator, not just an advocate.',
              'It outlines the legal position, states what avoids litigation, gives a chance to respond/settle, and satisfies procedural requirements affecting costs/admissibility (e.g. PD18.1).',
            ],
          },
          {
            heading: 'Preparation & structure',
            items: [
              'Identify the primary purpose (e.g. demand payment) and any secondary purpose (preserve relationship, clarify facts, propose settlement) before drafting.',
              'Follow a deliberate structure — no stream-of-consciousness. Simple, factual, intentional.',
            ],
          },
          {
            heading: 'Opening',
            items: [
              'Professional letter formatting: date, recipient, subject line.',
              'Introduce sender, client, and reason for writing — e.g. "We act for [Client]. We are instructed to write to you concerning a contract entered into on [date]..."',
            ],
          },
          {
            heading: 'Factual background',
            items: [
              'State material facts clearly, chronologically, in active voice — who did what, and when.',
              'No speculation, exaggeration, or emotive language — let the facts speak.',
            ],
          },
          {
            heading: 'Legal basis',
            items: [
              'Explain the legal basis simply and assertively — "Your failure to [breach] constitutes a breach of contract. Our client is entitled to..."',
              'Include a statutory/contractual reference where appropriate; avoid legalese, "it appears", "it is arguable" — project confidence, not doubt.',
            ],
          },
          {
            heading: 'Demand, warning & closing',
            items: [
              'State precisely what is demanded, with the exact amount and a clear deadline (e.g. 7/14 days); may add interest, costs, or an ADR proposal.',
              'If it is a final warning, say so plainly and proportionately — no dramatic threats.',
              'Close restating willingness to resolve; "Yours faithfully"/"Yours sincerely" as appropriate; list enclosures (contract, correspondence, invoices).',
            ],
          },
          {
            heading: 'Style, editing & final checks',
            items: [
              'Short sentences, plain English, no jargon or contractions, one topic per paragraph, clear signposting ("Turning to...", "In summary").',
              'Proofread for grammar/spelling/punctuation; remove every unnecessary word.',
              'Before sending: accurate and complete, clear response timeline, all enclosures included, dated and signed.',
            ],
          },
          {
            heading: 'Key points to recall',
            items: [
              "Be clear about the letter's purpose before you start.",
              'Follow a deliberate structure: opening, facts, legal basis, demand, warning, closing.',
              'Be concise, objective and professional in tone.',
              'Avoid legalese, exaggeration and speculation.',
              'Edit hard for clarity, brevity and accuracy.',
            ],
          },
        ],
      },
      lifecycleReference: {
        title: 'Appendix A — Lifecycle of a Civil Claim',
        external: true,
        note: 'Separate 35-page reference document (uploaded to Moodle) — linked here as a reading item, not transcribed.',
      },
      undertakingForm: {
        title: 'Undertaking Form (Standardised Clients Interviewing Exercise)',
        body: 'Return to your tutor during SG1 (9 or 10 September 2026), or — only if unable to — email it to Mr Frederick Lo (ctflo99@hku.hk) by 5:00pm Friday 11 September 2026. Failing to submit it, or failing to agree to its terms, means 0 out of 5 marks on the Interviewing Exercise.',
        checkboxes: [
          'Agree not to discuss or share the contents of my Interviewing Exercise session (incl. my own notes) with any other student or third party until after 10:00pm on 18 September 2026',
          'Consent to my performance being video-recorded for educational purposes',
        ],
        fields: ['Full Name', 'Signed', 'Date', 'Group no.'],
      },
    },

    sessions: {
      LG1: {
        kind: 'LG',
        date: '2026-09-02',
        time: '13:00-15:30',
        mode: 'Face-to-face',
        authors: ['Julienne Jen', 'Darcy Lynn Davison-Roberts', 'Ophelia Chan'],
        parts: [
          {
            partLetter: 'A',
            title: 'Introduction to the Course',
            instructor: { name: 'Darcy Lynn Davison-Roberts', email: 'dldavrob@hku.hk', hours: 'Thursdays 17:00-19:00' },
            objectives: [
              'The course objectives and how the Civil Litigation course will be taught',
              'The knowledge and skills students will acquire and practise',
              'What is expected of students',
              'Methods of assessment',
            ],
          },
          {
            partLetter: 'B',
            title: 'Taking Instructions on a New Case & Drafting Letters Before Action',
            instructor: { name: 'Ophelia Chan', email: 'cyyo@hku.hk', hours: 'Wednesdays 11:00-17:00' },
            objectives: [
              'Distinguish the two basic types of legal problem solving',
              'Explain the process model of legal problem solving for conducting civil claims',
              'Apply the legal problem-solving skill through a case study',
              'Draft a letter before action',
            ],
          },
        ],
        topicsCovered: [
          'Two basic types of legal problem solving — Blocking Conflict vs Playing Out Conflict',
          '5-stage Process Model of Legal Problem Solving ("PG-FLAP"): Problem/goal identification, Fact investigation, Legal issue identification and assessment, Advice and decision making, Planning and implementation',
          'Drafting a Letter Before Action',
        ],
        prep: {
          readings: ['This lecture outline', 'Negligence Case File, Bundle A', 'Contract Case File', 'Appendix 2: Drafting Letters Before Action Skills Guide'],
          activities: [
            { title: 'Exercise 1: Greenhouse Effective Petroleum Company Limited', instructions: 'Read and complete before class' },
          ],
        },
        keyTakeaways: [
          'PG-FLAP is the way to handle legal problems.',
          'Pre-action conduct (e.g. a letter before action) can have implications as to costs.',
        ],
        exercises: [
          {
            id: 'ex1',
            title: 'Exercise 1 — Greenhouse Effective Petroleum Company Limited',
            factPattern: "You are an assistant solicitor at Messrs. Black, Green & White, approached by Mr George Po, Managing Director of Greenhouse Effective Petroleum Company Limited (\"Greenhouse\"). A traffic accident on 13 January 2020 at Greenhouse's Shatin Petrol Service Station: a silver Mercedes Benz (plate GT 3194) lost control entering the station, colliding with a pump and cash register and injuring a staff member. Both had to be replaced, costing at least a few hundred thousand dollars. Police attended and took statements from the petrol serviceman (Chan Mo Gu) and the supervisor (Wong Chu Yum), neither of whom retained copies. Po does not know the vehicle owner's identity but wants to recover Greenhouse's losses.",
            questions: [
              'How should you advise Greenhouse?',
              'What should Greenhouse do now?',
              'Who should Greenhouse recover against?',
              'How should Greenhouse pursue its cause of action, if any?',
              'What further information or investigation is required?',
            ],
          },
        ],
        fullNotes: [
          {
            heading: 'Course objectives & design strategy',
            bullets: [
              'Two strands taught together: (1) civil procedure rules, and (2) civil litigation drafting/problem-solving skills.',
              'Delivered through LGs, SGs, video recordings, and review/Q&A sessions.',
              'Procedure rules: taught via LG in week one, then practised via SG later.',
              'Skills sequencing: interviewing and drafting an LBA are taught early; drafting of pleadings, affidavits, summonses and orders comes progressively later.',
              'Two realistic case files (Contract and Negligence) run throughout the course so you see how procedural rules and skills apply at different stages of real litigation — both available on Moodle from day one.',
            ],
          },
          {
            heading: 'What a "Skills Guide" is for',
            bullets: [
              'A skills guide sets out criteria for a skill, guidance on performing it, and criteria for assessing it.',
              "It's meant to be applied flexibly across different problems, not as a rigid checklist for one situation — use it to guide your own drafting and for self-assessment, with minimal reliance on precedents or sample answers.",
            ],
          },
          {
            heading: '5-level case analysis model',
            table: {
              headers: ['Level', 'Focus', 'Why it matters'],
              rows: [
                ['1', 'Area of law', 'Frames which body of law governs the problem'],
                ['2', 'Cause of action / remedy', 'What the client can actually claim'],
                ['3', 'Legal ingredients', 'The elements that support the cause of action'],
                ['4', 'Material facts', 'The facts needed for each ingredient — drives pleadings'],
                ['5', 'Evidence', 'What proves each material fact, and how — drives affidavits'],
              ],
            },
            bullets: ['Useful for assessing merits, deciding what further evidence is needed, drafting pleadings (Level 4), and preparing affidavits (Level 5).'],
          },
          {
            heading: 'Case Analysis, Research, Problem Solving & Fact Management',
            bullets: [
              'The hardest transition in the course is from theoretical recall to practical analysis, investigation and application — these skills are used together throughout, not learned in isolation.',
              "Build the habit of preparing, for every case (whether or not an exercise expressly asks for it): a Dramatis Personae (list of people involved), a Chronology of Events, a succinct summary of the client's case, and a Skeletal Plan for any drafting.",
            ],
          },
          {
            heading: 'Conducting claims, LBAs, interviewing, pleadings, affidavits, summonses',
            table: {
              headers: ['Stage', 'What you learn', 'Format / notes'],
              rows: [
                ['LG', 'The overall litigation picture', 'Plus textbook reading'],
                ['SG homework', 'Draft a Letter Before Action, in groups', ''],
                ['LG2 + SG2', 'Interviewing skills', 'Compulsory interviewing exercise at SG2 — up to 5% of the aggregate, happens once, marks carry to any supplementary exam'],
                ['SG', 'Draft pleadings using the 5-level model, not precedents', 'Tutor feedback plus sample drafts provided'],
                ['SG', 'Draft affidavits', 'First affidavit: oral review. Second: individual written feedback. Ex-parte affidavits raise full-and-frank-disclosure duties.'],
                ['SG', 'Draft summonses / orders', 'Taught alongside affidavits, once affidavit skills are covered'],
              ],
            },
          },
          {
            heading: 'Professionalism & written assessments',
            bulletGroups: [
              {
                heading: 'Conduct expected of you',
                items: [
                  'Be punctual, treat others with courtesy, prepare thoroughly.',
                  'Notify your tutor in advance of any inability to attend an SG or submit on time.',
                ],
              },
            ],
            table: {
              headers: ['Component', 'Weight', 'Covers'],
              rows: [
                ['Knowledge paper', '47.5%', 'Problem questions on procedure & case analysis'],
                ['Drafting paper', '47.5%', 'Drafting / planning questions'],
                ['Interviewing exercise', 'up to 5%', 'Standardised Client Interview — happens once, see SG2'],
              ],
            },
            bullets: [
              'Pass mark: at least 50% in aggregate across both papers plus the interviewing exercise — not necessarily 50% on each paper individually.',
              'Re-examination (if allowed) only requires re-sitting a paper scored below 50%; the other paper’s mark carries over.',
            ],
          },
          {
            heading: 'Civil Advocacy split, materials & submission requirements',
            bullets: [
              'PCLL8010 = 70% Civil Litigation + 30% Civil Advocacy.',
              'Course materials (Case Files, LG outlines, SG activity plans) are on Moodle and set out what to prepare before each class.',
              'Submissions: soft copy via Moodle, with name and group number in the top-left corner.',
              'A completed pro forma declaration must be the front page of the same document — assignments without it are not marked.',
            ],
          },
          {
            heading: 'Part 1B — PG-FLAP explained in depth',
            bullets: [
              'Problem solving is central to legal competence: solving problems satisfactorily, lawfully, ethically — drawing on knowledge, skills and professional attitude.',
              'To solve legal problems you draw on Knowledge (legal and non-legal; substantive, transactional, procedural), Skills (core and specialised), and Attitudes (professionalism, dedication, self-motivation).',
              'Two basic types of legal problem: Blocking Conflict (foreseeing and avoiding conflict — non-contentious) vs Playing Out Conflict (conflict already exists, contentious, litigation anticipated).',
            ],
            diagram: {
              title: 'PG-FLAP — the 5-stage process model',
              steps: [
                { label: 'Problem / goal identification', detail: "What does the client want or need? What's the obstacle? The problem itself can change as you learn more." },
                { label: 'Fact investigation', detail: 'Via interviews, correspondence, document analysis — iterating as new legal issues surface, and considering what further information or searches are needed.' },
                { label: 'Legal issue identification & assessment', detail: 'Research the issues, then assess the merits.' },
                { label: 'Advice & decision-making', detail: 'Develop and evaluate options (sue, settle, mediate, negotiate, admit fault, withdraw, or continue/renegotiate); weigh non-legal factors too (peace of mind, cost in time and money); choose client-centred (client decides) or lawyer-centred (you recommend).' },
                { label: 'Planning & implementation', detail: 'A concrete action plan: who does what, when, how.' },
              ],
            },
          },
          {
            heading: 'Letter Before Action — Q&A',
            qa: [
              { q: 'Is an LBA legally required before starting proceedings?', a: 'No general rule requires it — the exception is personal injury claims (PD18.1). But the court’s costs discretion (O.62 rr.5(1)(e)/5(2)(d)) can penalise unreasonable pre-action conduct, so send one unless there’s a risk the defendant will dissipate assets.' },
              { q: 'Who can send one, and is there a required form?', a: 'Anyone can send an LBA — there is no standard form or specific content requirement (see the Skills Guide).' },
              { q: 'Is there a fixed response time, or a consequence for silence?', a: 'No fixed response time, though 14–28 days is reasonable; there is no formal consequence for the recipient staying silent.' },
              { q: 'What is it actually for?', a: 'To save costs if liability isn’t disputed or settlement is possible, iron out issues, and test the waters.' },
            ],
          },
        ],
        cloze: [
          { text: 'The 5-stage process for legal problem solving is known by the acronym {{PG-FLAP}}: Problem/goal identification, Fact investigation, Legal issue identification and assessment, Advice and decision-making, Planning and implementation.' },
          { text: 'The two basic types of legal problem are {{Blocking Conflict}} (non-contentious — foreseeing and avoiding conflict) and {{Playing Out Conflict}} (contentious — conflict already exists).' },
          { text: 'In the 5-level case analysis model, Level {{4}} is the material facts for each legal ingredient (drives pleadings), and Level {{5}} is the evidence for each material fact (drives affidavits).' },
          { text: 'An LBA is not generally required before starting proceedings, except for {{personal injury}} claims under {{PD18.1}}.' },
          { text: 'A party who unreasonably skips an LBA risks an adverse costs order under {{O.62 rr.5(1)(e)/5(2)(d)}}.' },
          { text: 'To pass Civil Litigation you must clear two thresholds: 50%+ overall, AND 50%+ of the {{written papers}} component alone — a strong interviewing mark cannot rescue weak written papers.' },
          { text: "Build the habit of preparing, for every case, a {{Dramatis Personae}}, a {{Chronology of Events}}, a succinct case summary, and a {{Skeletal Plan}} for any drafting." },
        ],
        referenceIds: ['proFormaDeclaration', 'skillsGuideLBA'],
      },

      SG1: {
        kind: 'SG',
        date: '2026-09-09/10',
        time: '12:45-14:45 (Gp1-13) / 15:00-17:00 (Gp14-26)',
        skills: 'Problem Solving & Drafting Letter Before Action',
        objectives: [
          "Enhance understanding of concepts such as jurisdiction, pleadings, standing and evidence",
          'Work effectively with others to analyse legal problems and apply relevant procedural rules',
          'Draft a letter before action (LBA) for the client',
        ],
        prepChecklist: [
          { id: 'attend-lg1', label: 'Attend Civil Litigation LG1' },
          { id: 'read-case-file', label: 'Read the Negligence Case File — Greenhouse Effective Petroleum Co Ltd v Inn Convenient Co Ltd & anor, Batch A pp 1-62' },
          { id: 'read-appendix-a', label: 'Read and review Appendix A — Lifecycle of a civil claim' },
          { id: 'ex1-commencement', label: 'Prepare Exercise 1: Commencement of proceedings and jurisdiction (4 questions)' },
          { id: 'ex1-pleadings', label: 'Prepare Exercise 1: Documents and pleadings (2 questions)' },
          { id: 'ex1-standing', label: 'Prepare Exercise 1: Standing and Evidence (2 questions)' },
          { id: 'ex1-strategic', label: 'Prepare Exercise 1: Strategic and Practical Considerations (3 questions)' },
          { id: 'read-appendix-bc', label: 'Read Appendices B & C (LBA student guide + skills guide) before Exercise 2' },
        ],
        exercises: [
          {
            id: 'ex1',
            title: 'Exercise 1 — Civil Procedure Application (prep questions)',
            questionGroups: [
              {
                heading: 'Commencement of proceedings and jurisdiction',
                questions: [
                  'In which court should Greenhouse commence proceedings if the claimed loss is HK$571,300? Provide your reasons.',
                  'What originating process should be used to commence the claim, and why?',
                  'Who would be the appropriate plaintiff: Greenhouse Effective Petroleum Company Limited or its sister company?',
                  'Can the defendants be sued jointly? Explain the basis of any potential joint liability.',
                ],
              },
              {
                heading: 'Documents and pleadings',
                questions: [
                  'When a Writ is issued, what must it be indorsed with?',
                  "What court documents should be filed to preserve Greenhouse's position if the limitation period is close to expiry but investigations are ongoing?",
                ],
              },
              {
                heading: 'Standing and Evidence',
                questions: [
                  "What evidence would be required to support Greenhouse's standing to sue for the repair invoice issued by its sister company?",
                  'What is the function of the written board resolution included in the case file?',
                ],
              },
              {
                heading: 'Strategic and Practical Considerations',
                questions: [
                  'If Inn Convenient is insured, what are the implications for the conduct of proceedings?',
                  "Why did the solicitors consider whether Inn Convenient and Michael Shu were 'worth suing' before advising their client to proceed?",
                  'Why was it important to explain the risks of cost recovery even if Greenhouse succeeded in court? What practice direction/procedural rule justifies this?',
                ],
              },
            ],
          },
        ],
        activities: [
          { title: 'Exercise 1 — Civil Procedure Application: sub-groups of 2-3 discuss selected questions; tutor role-plays the supervising partner/client and directs discussion to jurisdiction, standing, limitation, pleadings, service, evidence and strategy.' },
          { title: 'Exercise 2 — Drafting a Letter Before Action: two drafting sub-groups, one addressed to Inn Convenient Company Limited (vehicle owner), the other to Michael Shu (driver). One representative per sub-group submits the final draft with a completed declaration via Moodle.', deadlineId: 'PCLL8010-hw-sg1' },
          { title: 'Exercise 3 — Complete and hand in the Undertaking Form for the Interviewing Exercise (Appendix D).', deadlineId: 'PCLL8010-undertaking' },
        ],
        cloze: [
          { text: "SG1's skill focus is {{Problem Solving & Drafting Letter Before Action}}." },
          { text: 'Exercise 2 has each drafting sub-group submit its final LBA draft with a completed {{declaration}} via Moodle.' },
          { text: 'The Undertaking Form for the Interviewing Exercise must reach Mr Frederick Lo by {{5:00pm Friday 11 September 2026}} if not handed to your tutor during SG1.' },
        ],
        referenceIds: ['lifecycleReference', 'lbaStudentGuide', 'skillsGuideLBA', 'undertakingForm'],
      },

      SG2: {
        kind: 'SG',
        date: '2026-09-17/18',
        time: 'Allocated slot, 09:30-18:00 (20 min each) — exact time/venue posted to Moodle by 11 Sept',
        skills: 'Client Interviewing',
        objectives: [
          'Prepare and plan effectively to interview a client and obtain instructions on a new case',
          'Understand and develop basic interviewing skills for obtaining further instructions on a new matter',
        ],
        compulsory: true,
        weight: 'Up to 5% of the Civil Litigation aggregate — happens once; marks carry to any supplementary exam',
        swapProcedure: "If unable to attend your allocated slot: arrange a swap with another student, then email all 3 Course Co-ordinators AND Mr Frederick Lo (ctflo99@hku.hk), copying the other student, by 5:00pm Tuesday 15 September 2026 with details and reasons.",
        prepChecklist: [
          { id: 'undertaking-form', label: 'Complete the Undertaking Form (Appendix D of the SG1 Activity Plan)' },
          { id: 'review-lg2', label: "Review Civil Litigation LG2's outline/notes on interviewing and the Standardised Client Interviewing Criteria" },
          { id: 'review-fact-pattern', label: 'Prepare for the interview with the client documents (demand letter & loan agreement) — bring sufficient copies' },
        ],
        factPattern: {
          client: 'Kenny Man',
          role: 'Trainee solicitor at Messrs. Pang, Chan, Law and Lo',
          instructingPartner: 'Jennifer Jong',
          documents: ['Demand letter', 'Loan agreement'],
          note: 'A Standardised Client will act as Kenny Man for the exercise; a firm/conflict check has already been assumed complete.',
        },
        duringAfter: [
          'During: ask the questions needed to represent Kenny Man in this new matter; the standardised client completes a feedback form based on the Standardised Client Interviewing Criteria.',
          'After: honour the signed Undertaking — do not discuss or share the session (or your notes) with anyone until after 10:00pm on 18 September 2026. Written feedback follows in late November/early December.',
          'Conduct: treat the exercise seriously and professionally — misbehaviour, breaching the signed Undertaking, or not showing up without a valid reason can lead to disciplinary action.',
        ],
        cloze: [
          { text: 'The signed Undertaking means you must not discuss or share the interviewing session (or your notes) with anyone until after {{10:00pm on 18 September 2026}}.' },
          { text: 'A slot-swap request must reach all 3 Course Co-ordinators AND {{Mr Frederick Lo}}, copying the other student, by {{5:00pm Tuesday 15 September 2026}}.' },
          { text: 'The Standardised Client Interview is worth up to {{5%}} of the Civil Litigation aggregate, and only happens {{once}}.' },
          { text: 'Skipping the Interviewing Exercise without a valid reason, or breaching the signed Undertaking, can lead to {{disciplinary action}}.' },
        ],
        referenceIds: ['undertakingForm'],
        assessmentRef: 'assessment-interview',
      },
    },
  },
};
